module: SwiftKuerySQLite
author: IBM
github_url: https://github.com/Kitura/Swift-Kuery-SQLite

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SwiftKuerySQLite.xcodeproj, -target, SwiftKuerySQLite]


